In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('customer.csv')

In [5]:
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [7]:
df =df.iloc[:,2:]

In [9]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.drop('purchased', axis=1),df['purchased'],test_size=0.3)

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [18]:
y_train


45    Yes
44     No
25     No
10    Yes
12     No
2      No
16    Yes
31    Yes
41    Yes
24    Yes
22    Yes
33    Yes
5     Yes
3      No
42    Yes
37    Yes
35    Yes
48    Yes
23     No
47    Yes
19    Yes
7     Yes
13     No
17    Yes
32    Yes
15     No
6      No
27     No
4      No
46     No
49     No
39     No
34     No
26     No
11    Yes
38     No
8      No
28     No
9     Yes
30     No
Name: purchased, dtype: object

In [19]:
x_train

review education
45     Poor        PG
44  Average        UG
25     Good    School
10     Good        UG
12     Poor    School
2      Good        PG
16     Poor        UG
31     Poor    School
41     Good        PG
24  Average        PG
22     Poor        PG
33     Good        PG
5   Average    School
3      Good        PG
42     Good        PG
37  Average        PG
35     Poor    School
48     Good        UG
23     Good    School
47     Good        PG
19     Poor        PG
7      Poor    School
13  Average    School
17     Poor        UG
32  Average        UG
15     Poor        UG
6      Good    School
27     Poor        PG
4   Average        UG
46     Poor        PG
49     Good        UG
39     Poor        PG
34  Average    School
26     Poor        PG
11     Good        UG
38     Good    School
8   Average        UG
28     Poor    School
9      Good        UG
30  Average        UG

In [20]:
from sklearn.preprocessing import OrdinalEncoder

In [22]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [23]:
oe

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [24]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [29]:
x_train =oe.transform(x_train)


C:\python3.10\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [28]:
x_train

array([[0., 2.],
       [1., 1.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [0., 1.],
       [0., 0.],
       [2., 2.],
       [1., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [2., 2.],
       [1., 2.],
       [0., 0.],
       [2., 1.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [0., 0.],
       [2., 1.],
       [1., 1.]])

In [30]:
x_test =oe.transform(x_test)

In [31]:
x_test

array([[1., 2.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [2., 1.],
       [2., 0.],
       [0., 1.],
       [1., 1.]])

In [32]:
from sklearn.preprocessing import LabelEncoder    # label encoding output column pa lgaty hai


In [33]:
le = LabelEncoder()

In [35]:
le.fit(y_train)

LabelEncoder()

In [36]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [37]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)


In [38]:
y_train

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0])